import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;

/**
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 */
public class FindTheDifference {

    public static void main(String[] args) {
        System.out.println(findTheDifference3("ae", "aea"));
    }

    public char findTheDifference(String s, String t) {
        char[] sC = s.toCharArray();
        char[] sT = t.toCharArray();

        Arrays.sort(sC);
        Arrays.sort(sT);

        for(int i = 0; i < s.length(); i++){
            if(sC[i] != sT[i])return sT[i];
        }

        return sT[t.length()-1];
    }

    public static char findTheDifference2(String s, String t) {

        HashMap<Character, Integer> map = new HashMap<>();
        HashMap<Character, Integer> map2 = new HashMap<>();
        HashSet<Character> set = new HashSet<>();

        for(char c : s.toCharArray()){
            if(map.containsKey(c)){
                int num = map.get(c)+1;
                map.put(c, num);
            }
            else map.put(c, 1);
        }

        for(char c : t.toCharArray()){
            if(map2.containsKey(c)){
                int num = map2.get(c)+1;
                map2.put(c, num);
            }
            else map2.put(c, 1);

            set.add(c);
        }

        char ret = 'r';

        for(char c : set){            
            if(map.get(c) != map2.get(c)){
                ret = c; 
                break; 
            }         
        }


        return ret;
    }

    public static char findTheDifference3(String s, String t) {
        int k = 0;
        int j = 0;
        for (int i = 0; i<s.length(); i++){
            k+=s.charAt(i);
            j+=t.charAt(i);
        }
        j+=t.charAt(s.length());
        return (char) (j-k);
    }

    /**
     * 0 <= s.length <= 1000
     * t.length == s.length + 1
     * s and t consist of lower-case English letters.
     */
}
